---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
  - job_name: API_Request_User_Count
    static_configs:  ##Provide service name
      - targets: ["go-prometheus-grafana:8081"]